import logging
from typing import Optional, Dict, Any
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from app.models.schema_models import (
    File, User, Team, TeamMember, QualifiedDownload, SystemSetting
)
from app.services.wallet.service import WalletService
from app.core.config import settings

logger = logging.getLogger("rage.revenue.engine")

class RevenueEngine:
    """
    Central Revenue Engine for RAGE Cloud.
    Calculates dynamic revenue splits among Creators, Teams, and Platform
    and commits entries to the immutable ledger.
    """

    @staticmethod
    async def get_setting(key: str, default: float, session: AsyncSession) -> float:
        stmt = select(SystemSetting).where(SystemSetting.key == key)
        res = await session.execute(stmt)
        record = res.scalar_one_or_none()
        if record:
            try:
                return float(record.value)
            except ValueError:
                pass
        return default

    @classmethod
    async def process_qualified_download_revenue(
        cls,
        download_id: str,
        file: File,
        fraud_score: int,
        session: AsyncSession,
        gross_cpm_revenue: float = 0.15 # Baseline estimated ad CPM revenue share for this qualified visit
    ) -> Optional[QualifiedDownload]:
        """
        Distributes revenue generated by a verified qualified download event.
        """
        # Fetch dynamic split configuration
        creator_pct = await cls.get_setting("creator_revenue_percent", settings.CREATOR_REVENUE_PERCENT, session)
        platform_pct = await cls.get_setting("platform_revenue_percent", settings.PLATFORM_REVENUE_PERCENT, session)

        # Normalize percentages
        total_pct = creator_pct + platform_pct
        creator_ratio = creator_pct / total_pct

        creator_gross_revenue = round(gross_cpm_revenue * creator_ratio, 4)

        # If file is associated with a team, distribute to team members
        if file.team_id:
            team_members_stmt = select(TeamMember).where(TeamMember.team_id == file.team_id)
            tm_res = await session.execute(team_members_stmt)
            members = tm_res.scalars().all()

            if members:
                for member in members:
                    if member.revenue_share_percent > 0:
                        member_amt = round(creator_gross_revenue * (member.revenue_share_percent / 100.0), 4)
                        if member_amt > 0:
                            m_wallet = await WalletService.get_or_create_wallet(member.user_id, session)
                            await WalletService.credit_balance(
                                wallet_id=m_wallet.id,
                                amount=member_amt,
                                transaction_type="CREATOR_REVENUE",
                                description=f"Team earnings ({member.revenue_share_percent}%) for file '{file.name}'",
                                session=session,
                                reference_type="download",
                                reference_id=download_id
                            )
            else:
                # Fallback to file owner if no members
                owner_wallet = await WalletService.get_or_create_wallet(file.owner_id, session)
                await WalletService.credit_balance(
                    wallet_id=owner_wallet.id,
                    amount=creator_gross_revenue,
                    transaction_type="CREATOR_REVENUE",
                    description=f"Qualified download revenue for '{file.name}'",
                    session=session,
                    reference_type="download",
                    reference_id=download_id
                )
        else:
            # Direct creator attribution
            owner_wallet = await WalletService.get_or_create_wallet(file.owner_id, session)
            await WalletService.credit_balance(
                wallet_id=owner_wallet.id,
                amount=creator_gross_revenue,
                transaction_type="CREATOR_REVENUE",
                description=f"Qualified download revenue for '{file.name}'",
                session=session,
                reference_type="download",
                reference_id=download_id
            )

        # Create record in qualified_downloads
        qd = QualifiedDownload(
            download_id=download_id,
            file_id=file.id,
            creator_id=file.owner_id,
            team_id=file.team_id,
            qualification_status="QUALIFIED",
            fraud_score=fraud_score,
            revenue_generated=gross_cpm_revenue,
            creator_revenue=creator_gross_revenue
        )
        session.add(qd)
        await session.flush()
        return qd

    @classmethod
    async def process_content_purchase_revenue(
        cls,
        file: File,
        buyer_id: str,
        gross_amount: float,
        session: AsyncSession
    ) -> Dict[str, float]:
        """
        Distributes revenue from a user purchasing access to a paid file.
        """
        creator_pct = await cls.get_setting("creator_revenue_percent", settings.CREATOR_REVENUE_PERCENT, session)
        platform_pct = await cls.get_setting("platform_revenue_percent", settings.PLATFORM_REVENUE_PERCENT, session)

        total_pct = creator_pct + platform_pct
        creator_amount = round(gross_amount * (creator_pct / total_pct), 2)
        platform_amount = round(gross_amount - creator_amount, 2)

        owner_wallet = await WalletService.get_or_create_wallet(file.owner_id, session)
        await WalletService.credit_balance(
            wallet_id=owner_wallet.id,
            amount=creator_amount,
            transaction_type="PURCHASE",
            description=f"Paid content sale for '{file.name}' by buyer #{buyer_id[:8]}",
            session=session,
            reference_type="file_purchase",
            reference_id=file.id
        )

        return {
            "creator_amount": creator_amount,
            "platform_amount": platform_amount
        }
